
services:
  - type: web
    name: wallet-connect-app
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /api/health
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
