services:
  - type: web
    name: wallet-connect-app
    env: node
    buildCommand: |
      npm ci
      npm run build
      mkdir -p server/public
      cp -r dist/* server/public/
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health
    disk:
      name: data
      mountPath: /data
      sizeGB: 5  # Increase disk size for more storage
    autoscaling:
      min: 1      # Always have at least one instance
      max: 1      # Limit to one instance to avoid consistency issues
    persistentStorage:
      enabled: true
      mountPath: /data
      sizeGB: 5